### ISSUE TITLE
Pliz Halp! My Code Not Working 😤

### ISSUE THREAD

**Issue by JE-FH** [Rasteplads/FestFriend#1] opened 2024-03-27 14:52 UTC
Hello Sirs,

I am facing a big problem with your softwair. I am trying to run the code but it is not working. When I press the button, nothing happens. It's like a dead fish 🐟. I don't understand what is the problem. Pliz to help me, I need the code to work urgently.

Thank you muchly. 🙏

Best,
Confused Coder

**Comment by JE-FH** [comment] 2024-03-27 14:55
Me having mega issue with ur app FestFriend. Me try use in spot with no bars, but it's like, dead. It should find buds even when net's zilch, but it's like, "nah." Can u fix super fast? Me at fest now and need find my mates.

**Comment by alexsteffensen** [comment] 2024-04-05 11:48
Hello JE-FH

We are working on the issue, please punch cold water in your blood.

Sorry for my bad england

Best,
FestFriend Developer

**Comment by laurits-mumberg** [comment] 2024-04-05 11:49
MAX FEST APPEN LÅLÅLÅ

**Comment by MJHC** [comment] 2024-04-05 11:49
# Dear Confused Coder

Thank you for bringing this matter to our attention. We sincerely apologize for any inconvenience you've experienced with our software. Rest assured, we understand the urgency of your request and are committed to resolving it promptly.

We acknowledge your frustration with the current functionality of our software, and we're dedicated to ensuring that it performs optimally for all users. Our team is actively investigating the reported issue to identify the root cause and implement a solution.

However, please understand that as a large open-source project with a significant user base, we are currently managing various priorities and commitments. This might result in some delays in addressing individual issues. Nevertheless, please be assured that your concern has been duly noted and will be addressed as soon as possible.

In the meantime, if feasible, we recommend exploring alternative solutions or workarounds that might mitigate the impact of the issue you're encountering.

Once again, we apologize for any inconvenience caused and appreciate your patience and understanding as we work towards a resolution. If you have any further questions or require assistance, please don't hesitate to reach out.

Thank you for your continued support and feedback.

Best regards

**Comment by laurits-mumberg** [comment] 2024-04-05 11:51
Hey there, don't sweat it!  Forget the fancy titles, we're all just Droppers on the Battle Bus here.  Sounds like your loot code is acting like a downed Shield Potion – no good!  Don't worry, even the best Builders run into bugs sometimes. Here's the skinny:

    Your "button" might not be linked up right to the code. Check your connections, make sure everything is synced tighter than a Turbo Build.
    The code itself could be buggy. Did a sneaky lil' Shadow Bomb of a typo get in there? Double check for any mistakes in your code, those rascals can cause havoc.
    Maybe the code needs more Slurp Juice to run! Sometimes fancy features need extra power. Make sure your program has the resources it needs to work.

If you're still stuck, try dropping into the Fortnite Forums. There's a ton of skilled Constructors there who can help you debug your code and get that Victory Royale!

Best of luck,

A Fellow Dropper

**Comment by JE-FH** [comment] 2024-04-12 12:36
> as a large open-source project with a significant user base, we are currently managing various p

# f u mister fister. submit PR!

**Closed as completed** 2024-04-16 11:50 UTC
